### PR TITLE
Moving RabbitMQ to 2.0.0

### PR DESCRIPTION
**Pull request by akshayAppd**

### CODE REVIEW

**Comment by satish-m** [comment]
1. Remove dictionary from config file and use alias
2. Need to improve test case coverage.

**Comment by venkatakonala** [comment]
1. Please add a CHANGELOG.md.
2. Please don't forget to update the metadata.json after the extension is released.
3. pom.xml needs to have copyright header(?) and I could not find LICENSE.txt and NOTICE.txt being packaged with RabbitMQ.
4. config.yml has to be reordered as per the standard to be followed by all extensions.
5. MetricConfig has metricType and this is being passed to the Metric class in commons. This means the commons will have default values for aggregationType, timeRollUpType and clusterRollUpType as metricType is not recognized. Also **the metricQualifiers are not identified for individual metrics**. 
6. Other comments in the code have been added as TODOs.

**Comment by kunalgupApDx** [comment]
The name of the directory is config which is not following the standard of conf in other extensions.
@akshayAppd

**Comment by venkatakonala** [comment]
TODOs
1. I see a RabbitMQCustomDashboard.png file in the repository. Is this required?
2. Can you please add the CHANGELOG.md for review as well.
3. MetricQualifiers for each metric has not been added in the metrics.xml yet.
4. "numberOfThreads" field needs to be configured to allow more servers, also a comment on number of threads to be added, when the customer wants to add more RabbitMQ servers.(See Redis for example).

**Comment by bhuvnesh17** [comment]
Remove that extra line right after the heading: This extension works only with the standalone machine agent.

Prerequisite:
Convert all open links to hyperlinks

Installation: 
make the text bold as done in the documentation guidelines

Configuration:
Suggestion: Maybe convert the list items into a smaller headings using the prefix ###

FIX the displayName in the second server listed in the sample config and make sure its not indented in the config file that you provide.

   - host: "localhost"
     port: 15673
     useSSL: false
     username: "guest"
     password: "guest"
 	     displayName: "displayName1" //The display name to be used for the metrics of this server, mandatory

Remove community and support sections in the bottom and add the VERSION section as listed in the documentation guidelines.

**Comment by venkatakonala** [comment]
1. Changed Hert Beat to HeartBeat, as per the coding documentation.
2. The metric qualifiers in the metrics.xml need to be discussed. I have conflicting views about the qualifiers specified for most of the metrics.
3. Also the "Running" metric in the OverviewMetricParser class(line70) needs to be discussed. I see that the metricPath is Clusters|<clusterName>|Nodes|Running.
4. TODOs in the code will be checked in.

**Comment by bhuvnesh17** [comment]
Documentation Review Part 2

1. Remove that extra line right after the heading: This extension works only with the standalone machine agent.

2. FIX the displayName in the second server listed in the sample config and make sure its not indented in the config file that you provide.

host: "localhost"
port: 15673
useSSL: false
username: "guest"
password: "guest"
        displayName: "displayName1" //The display name to be used for the metrics of this server, mandatory

3. convert the version section into a table

**Pull request merged**
